### PR TITLE
Update pages for Academy workshops (R and Python)

### PR DESCRIPTION
**Pull request by brendanhcullen**
@mine-cetinkaya-rundel I updated the pages for the R and Python workshops (heavily adapting from last year). If it's ok, I'd like to run this by a few Academy folks before merging. Ok if I ping you here when ready to merge? Thanks!

### CODE REVIEW

**Comment by mine-cetinkaya-rundel** [comment]
Sure!

**Comment by brendanhcullen** [comment]
@mine-cetinkaya-rundel thanks! good to go 👍

**Comment by brendanhcullen** [comment]
@mine-cetinkaya-rundel Thanks! This is good to go 👍 One question -- would you like me to specify the special registration deadline (6/24) for these workshops here?

**Comment by mine-cetinkaya-rundel** [comment]
Yes, would be good to add!

**Comment by brendanhcullen** [comment]
@mine-cetinkaya-rundel I added a callout box to highlight the start date and registration deadline. Happy to make any format tweaks (or of course feel free to tweak as you see fit). Thanks!

**Pull request merged**
